<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="oryksmower">
    
    <xacro:include filename="$(find oryksmower_description)/urdf/materials.xacro"/>
    <xacro:include filename="$(find oryksmower_description)/urdf/properties.xacro"/>
    <xacro:include filename="$(find oryksmower_description)/urdf/macros.xacro"/>
    <xacro:include filename="$(find oryksmower_description)/urdf/gazebo_properties.xacro"/>
    <xacro:include filename="$(find oryksmower_description)/urdf/gazebo_plugins.xacro"/>

   <!-- World link -->
   <!-- base_footprint is a fictious link(frame) that is on the ground right below base_link origin -->
   <!-- It is necessary as gazebo does not support inertia for the root link -->
   <!-- Do not call it world as it is reserved for robot that must be fixed to the world -->

   <link name="base_link">
   </link>

   <joint name="glue_robot_to_world" type="fixed">
      <origin xyz="0 0 0.1" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="chassis" />
   </joint>

   <!-- Base link -->
   <!-- Actual body/chassis of the robot -->

   <link name="chassis">
      <inertial>
         <mass value="${base_mass}" />
         <!-- the3x3 rotational inertia matrix -->
         <xacro:box_inertia m="${base_mass}" x="${base_lenght}" y="${base_width}" z="${base_height}" />
         <origin xyz="0 0 0" />
      </inertial>
      <visual>
         <origin xyz="0 0 0" rpy="0 0 0" />
         <geometry>
            <box size="${base_lenght} ${base_width} ${base_height}" />
         </geometry>
         <material name="Blue" />
      </visual>
      <collision>
         <origin xyz="0 0 0" rpy="0 0 0" />
         <geometry>
            <box size="${base_lenght} ${base_width} ${base_height}" />
         </geometry>
      </collision>
   </link>

   <!-- Wheel Definition for simulation -->
   
   <xacro:wheel fb="front" lr="right" parent="chassis" translateX="0.2" translateY="${-1*(base_width/2+0.04)}"       translateZ="-0.065" flipY="1"/>
   <xacro:wheel fb="front" lr="left"  parent="chassis" translateX="0.2" translateY="${1*(base_width/2+0.04)}"  translateZ="-0.065" flipY="1"/>
   <xacro:wheel fb="back"  lr="right" parent="chassis" translateX="-0.2" translateY="${-1*(base_width/2+0.04)}"      translateZ="-0.065" flipY="1"/>
   <xacro:wheel fb="back"  lr="left"  parent="chassis" translateX="-0.2" translateY="${1*(base_width/2+0.04)}" translateZ="-0.065" flipY="1"/>

   <!-- Lidar definition for simulation -->

   <link name="sweep_link" >
      <collision>
         <origin xyz="0 0 0" rpy="0 0 0" />
         <geometry>
            <box size="0.1 0.1 0.1" />
         </geometry>
      </collision>
      <visual>
         <origin xyz="0 0 0" rpy="0 0 0" />
         <geometry>
            <cylinder length="0.1" radius="0.05" />
         </geometry>
         <material name="Black" />
      </visual>
      <inertial>
         <mass value="1e-5" />
         <origin xyz="0 0 0" rpy="0 0 0" />
         <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
      </inertial>
   </link>


   <joint name="lidar_to_base" type="fixed" >
      <origin xyz="0.3 0 ${base_height/2+0.05}" rpy="0 0 0" />
      <parent link="chassis" />
      <child link="sweep_link" />
   </joint>

</robot>